### ISSUE TITLE
应该在打开二维码后限制玩家左右键互交，否则可以把地图放在展示框上...

### ISSUE THREAD

**Issue by polang233** [Iseason2000/SakuraPurchase#3]
如题，1.12.2 paper    使用java8
后台无报错   看了下源码好像并没有对左右键互交有处理

题外话:  我尝试QQ和b站私信你 不过都没有得到回复= =   请问是不方便吗还是其他情况

**Comment by Iseason2000** [comment]
忘记限制了，
b站私信没提示，qq没有消息，你确定你加我了？

**Comment by polang233** [comment]
qq确实是加了 上两星期吧owo

**Comment by Iseason2000** [comment]
> qq确实是加了 上两星期吧owo

你的qq是？

**Comment by polang233** [comment]
> 

2603738770    
github有点不太会用  老是按错东西= =
