### ISSUE TITLE
关于1.19.1以上出现异步调用线程问题

### ISSUE THREAD

**Issue by HeyChuYun** [Iseason2000/SakuraPurchase#5]
在你所写插件 at top.iseason.bukkit.sakurapurchaseplugin.util.MapUtil.generateQRMap(MapUtil.kt:119) ~[?:?]
的位置出现了问题
MapInitializeEvent cannot be triggered asynchronously from another thread.
是在订单生成后开始创建地图二维码出现的

**Comment by HeyChuYun** [comment]
我怀疑是你插件在异步使用了callEvent方法，该方法貌似不允许在异步调用

**Comment by Iseason2000** [comment]
> 我怀疑是你插件在异步使用了callEvent方法，该方法貌似不允许在异步调用

在spigot中是可以的，这是由其他服务端导致的，稍后我会改成同步调用

**Comment by Iseason2000** [comment]
请帮我测试一下 
[SakuraPurchasePlugin-1.1.4.zip](https://github.com/Iseason2000/SakuraPurchase/files/11361502/SakuraPurchasePlugin-1.1.4.zip)

**Comment by suiheng** [comment]
> 请帮我测试一下 [SakuraPurchasePlugin-1.1.4.zip](https://github.com/Iseason2000/SakuraPurchase/files/11361502/SakuraPurchasePlugin-1.1.4.zip)

还是不行，
MapInitializeEvent不能在另一个线程异步触发。这个问题发生在订单生成后，插件开始创建地图二维码的过程中。

插件在异步任务中使用了callEvent方法，而这个方法似乎不允许在异步线程中调用。

**Comment by windy664** [comment]
> 请帮我测试一下 [SakuraPurchasePlugin-1.1.4.zip](https://github.com/Iseason2000/SakuraPurchase/files/11361502/SakuraPurchasePlugin-1.1.4.zip)

经尝试 可以使用

**Comment by Iseason2000** [comment]
1.1.4
