### ISSUE TITLE
变量不起作用

### ISSUE THREAD

**Issue by windy664** [Iseason2000/SakuraPurchase#6]
`[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417
[17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: **** 
[17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`

如上日志
在config.yml中
`- points give %player% %10_amount%`
然则，这个%10_amount%并不起作用。

**Comment by Iseason2000** [comment]
> `[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417
> [17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: **** 
> [17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`
> 
> 如上日志
> 在config.yml中
> `- points give %player% %10_amount%`
> 然则，这个%10_amount%并不起作用。

返回结果是小数，请使用其他变量将小数转为整数

**Comment by windy664** [comment]
> > `[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417 [17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: ****  [17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`
> > 如上日志
> > 在config.yml中
> > `- points give %player% %10_amount%`
> > 然则，这个%10_amount%并不起作用。
> 
> 返回结果是小数，请使用其他变量将小数转为整数

%math_CEILING({10_amount})% 这样吗

**Comment by Iseason2000** [comment]
> > > `[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417 [17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: ****  [17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`
> > > 如上日志
> > > 在config.yml中
> > > `- points give %player% %10_amount%`
> > > 然则，这个%10_amount%并不起作用。
> > 
> > 
> > 返回结果是小数，请使用其他变量将小数转为整数
> 
> %math_CEILING({10_amount})% 这样吗

方式有很多种，你可以 /papi ecloud download Formatter 
使用 %formatter_number_round_<number>% ，具体就是 %formatter_number_round_%10_amount%%
使用 math 就是 %math_CEILING(%10_amount%)%
请注意默认的 %player% 和 %10_amount% 不是 papi的变量，在进行papi变量解析前就会被替换

**Comment by windy664** [comment]
> > > > `[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417 [17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: ****  [17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`
> > > > 如上日志
> > > > 在config.yml中
> > > > `- points give %player% %10_amount%`
> > > > 然则，这个%10_amount%并不起作用。
> > > 
> > > 
> > > 返回结果是小数，请使用其他变量将小数转为整数
> > 
> > 
> > %math_CEILING({10_amount})% 这样吗
> 
> 方式有很多种，你可以 /papi ecloud download Formatter 使用 %formatter_number_round_% ，具体就是 %formatter_number_round_%10_amount%% 使用 math 就是 %math_CEILING(%10_amount%)% 请注意默认的 %player% 和 %10_amount% 不是 papi的变量，在进行papi变量解析前就会被替换

然而 两个都不行 都提示必须是正数

**Comment by windy664** [comment]
![image](https://github.com/Iseason2000/SakuraPurchase/assets/81475218/471781cd-d299-4768-8f0d-b6c0adb55472)
请求把点券数值改为int型的  我拿点券自带的变量测试过了不行  但是我用我上一个PPRMB充值插件可以，这是PPRMB的配置
`# 兑换指令: 兑换后执行的命令,支持多条指令同时执行.
# 变量说明
# <player>: 玩家名称
# <rmb>: 提取金额
# <rmb>[倍数] 可实现数值翻倍, 如 <rmb>[100] 即 100 倍
# points give <player> <rmb>[10]的意思就是玩家充值1元给玩家10点券
# 下面为正式配置项.
服务器SID: 5952
服务器KEY: F06F8FF9DFE0CB10BBAEFACDC03F5799
兑换指令:
  - points give <player> <rmb>[10]
#  - say 用户 <player> 充值 <rmb>R 得到了 <rmb>[10] 点券`

**Comment by Iseason2000** [comment]
> > > > > `[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417 [17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: ****  [17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`
> > > > > 如上日志
> > > > > 在config.yml中
> > > > > `- points give %player% %10_amount%`
> > > > > 然则，这个%10_amount%并不起作用。
> > > > 
> > > > 
> > > > 返回结果是小数，请使用其他变量将小数转为整数
> > > 
> > > 
> > > %math_CEILING({10_amount})% 这样吗
> > 
> > 
> > 方式有很多种，你可以 /papi ecloud download Formatter 使用 %formatter_number_round_% ，具体就是 %formatter_number_round_%10_amount%% 使用 math 就是 %math_CEILING(%10_amount%)% 请注意默认的 %player% 和 %10_amount% 不是 papi的变量，在进行papi变量解析前就会被替换
> 
> 然而 两个都不行 都提示必须是正数

我的其他用户都能正常使用，请检查自己的问题，整数问题可以另加占位符，等待下个版本

**Comment by windy664** [comment]
> > > > > > `[17:58:15 INFO] [Console]: [SakuraPurchasePlugin] 用户 H** 发起 支付宝 支付,金额: 1.0 订单号: 16*******2417 [17:58:31 INFO] [Console]: [SakuraPurchasePlugin] 玩家 H** 订单 165*****212417 已完成支付(支付宝), 金额 1.0 命令组: ****  [17:58:31 INFO] [Console]: [§x点§x券] 数值必须为正数。`
> > > > > > 如上日志
> > > > > > 在config.yml中
> > > > > > `- points give %player% %10_amount%`
> > > > > > 然则，这个%10_amount%并不起作用。
> > > > > 
> > > > > 
> > > > > 返回结果是小数，请使用其他变量将小数转为整数
> > > > 
> > > > 
> > > > %math_CEILING({10_amount})% 这样吗
> > > 
> > > 
> > > 方式有很多种，你可以 /papi ecloud download Formatter 使用 %formatter_number_round_% ，具体就是 %formatter_number_round_%10_amount%% 使用 math 就是 %math_CEILING(%10_amount%)% 请注意默认的 %player% 和 %10_amount% 不是 papi的变量，在进行papi变量解析前就会被替换
> > 
> > 
> > 然而 两个都不行 都提示必须是正数
> 
> 我的其他用户都能正常使用，请检查自己的问题，整数问题可以另加占位符，等待下个版本

Config.performCommands中，我吧`command = command.replace(group, (amount * multiply).toString())
`改成`command = command.replace(group, (amount * multiply).toInt().toString())
`解决了。 papi搞得我一头雾水的。
